# Generated by Django 5.2.9 on 2026-01-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='client_profiles/'),
        ),
    ]
