# Generated by Django 5.2.9 on 2026-01-03 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('projects', '0002_project_canonical_url_project_meta_description_and_more'),
        ('testimonials', '0007_alter_testimonial_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='client.client'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
