# Generated by Django 5.1.4 on 2026-05-24 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_category_project_description_project_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
    ]
