# Generated by Django 6.0 on 2025-12-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='about',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='github',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='twitter',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_short',
            field=models.TextField(blank=True, help_text='Short about text for footer or meta description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text',
            field=models.TextField(blank=True, help_text='Copyright/footer text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Meta description for SEO', max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Override <title> tag', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_description',
            field=models.CharField(blank=True, help_text='Open Graph description', max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/seo/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title for social sharing', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_card',
            field=models.CharField(blank=True, default='summary_large_image', max_length=50),
        ),
    ]
