# Generated by Django 6.0 on 2025-12-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_sitesettings_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Upload favicon (16x16 or 32x32, max 100KB)', null=True, upload_to='site/'),
        ),
    ]
