# Generated by Django 6.0 on 2025-12-31 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0004_alter_sitesettings_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('block_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('html', 'HTML')], default='text', max_length=20)),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='content_blocks/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
