# Generated by Django 6.0 on 2025-12-22 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about_me', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='projects.skill'),
        ),
        migrations.AddField(
            model_name='journey',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='about_me.profile'),
        ),
        migrations.AddField(
            model_name='corevalue',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='about_me.profile'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='about_me.profile'),
        ),
    ]
