# Generated by Django 6.0 on 2025-12-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsettings',
            name='canonical_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutsettings',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='aboutsettings',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aboutsettings',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='aboutsettings',
            name='og_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='aboutsettings',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo/og/'),
        ),
        migrations.AddField(
            model_name='aboutsettings',
            name='og_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='aboutsettings',
            name='robots',
            field=models.CharField(blank=True, default='index,follow', help_text="Comma-separated robots directives, e.g. 'noindex,nofollow'", max_length=50),
        ),
    ]
