# Generated by Django 6.0 on 2025-12-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0003_aboutsettings_canonical_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, help_text='Primary contact email for the site owner', max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='career_start_date',
            field=models.DateField(blank=True, help_text='When your professional journey started', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='philosophy',
            field=models.TextField(blank=True, help_text='Write about your Philosophy'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='short_bio',
            field=models.TextField(blank=True, help_text='Short paragraph for homepage bento box'),
        ),
    ]
