# Generated by Django 5.2.9 on 2025-12-31 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0004_profile_email_profile_phone_profile_whatsapp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutsettings',
            options={'ordering': ('pk',), 'verbose_name': 'About Page Settings', 'verbose_name_plural': 'About Page Settings'},
        ),
    ]
