# Generated by Django 5.2.9 on 2025-12-31 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0005_alter_aboutsettings_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutsettings',
            options={'verbose_name': 'About Page Settings', 'verbose_name_plural': 'About Page Settings'},
        ),
    ]
