# Generated by Django 6.0 on 2025-12-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_message_subject_message_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated budget in USD', max_digits=10, null=True),
        ),
    ]
