# Generated by Django 6.0 on 2025-12-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contactsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsettings',
            name='sender_email',
            field=models.EmailField(default='osama2kabdullah@gmail.com', max_length=254),
        ),
    ]
