# Generated by Django 6.0 on 2025-12-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_contactsettings_sender_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsettings',
            name='sender_name',
            field=models.CharField(default='Osama Abdullah', help_text='Name displayed as the sender in emails', max_length=100),
        ),
    ]
