# Generated by Django 5.2.9 on 2025-12-31 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_contactsettings_sender_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactSettings',
        ),
    ]
