# Generated by Django 5.2.9 on 2025-12-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_delete_contactsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(default='Osama Abdullah', help_text='Name displayed as the sender in emails', max_length=100)),
                ('recipient_email', models.EmailField(default='abdullah21673@hotmail.com', max_length=254)),
                ('sender_email', models.EmailField(default='osama2kabdullah@gmail.com', max_length=254)),
            ],
            options={
                'verbose_name': 'Contact Settings',
                'verbose_name_plural': 'Contact Settings',
            },
        ),
    ]
