# Generated by Django 5.1.4 on 2026-07-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_contactsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deadline',
            field=models.CharField(blank=True, choices=[('urgent', "Urgent (moins d'une semaine)"), ('2_4_semaines', '2 à 4 semaines'), ('1_3_mois', '1 à 3 mois'), ('flexible', 'Flexible / pas de date précise')], max_length=30),
        ),
        migrations.AddField(
            model_name='message',
            name='is_quote_request',
            field=models.BooleanField(default=False, help_text='Coché si le message vient du formulaire de devis'),
        ),
        migrations.AddField(
            model_name='message',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='message',
            name='project_type',
            field=models.CharField(blank=True, choices=[('visuels', 'Création visuelle'), ('video', 'Montage vidéo'), ('thumbnail', 'Miniatures YouTube'), ('branding', 'Charte graphique'), ('web', 'Web design'), ('photo', 'Photo e-commerce'), ('autre', 'Autre')], max_length=30),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='recipient_email',
            field=models.EmailField(blank=True, help_text="Adresse qui reçoit une copie de chaque message/devis. Laisser vide pour utiliser l'email du profil.", max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='sender_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='sender_name',
            field=models.CharField(default='Abasse NIANG', help_text='Nom affiché comme expéditeur dans les emails automatiques', max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Budget estimé en euros (EUR)', max_digits=10, null=True),
        ),
    ]
