# Generated by Django 5.1.4 on 2026-07-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_message_deadline_message_is_quote_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='project_type',
            field=models.CharField(blank=True, choices=[('visuels', 'Création visuelle'), ('video', 'Montage vidéo'), ('thumbnail', 'Miniatures YouTube'), ('branding', 'Charte graphique'), ('web', 'Web design'), ('photo', 'Photo'), ('autre', 'Autre')], max_length=30),
        ),
    ]
