# Generated by Django 6.0 on 2025-12-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_heading', models.CharField(default='Leave a Testimonial for AlexDev', max_length=200)),
                ('submit_subheading', models.TextField(default='Your honest feedback is invaluable. Thank you for being a fantastic client!')),
                ('thanks_title', models.CharField(default='Thank You for Your Testimonial', max_length=200)),
                ('thanks_subheading', models.CharField(default='Testimonial Received', max_length=200)),
                ('thanks_message', models.TextField(default='Your testimonial has been received and will appear on the site after approval.')),
            ],
            options={
                'verbose_name': 'Testimonial Page Settings',
                'verbose_name_plural': 'Testimonial Page Settings',
            },
        ),
    ]
