# Generated by Django 5.2.9 on 2025-12-31 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0004_testimonialpagesettings_canonical_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonialpagesettings',
            options={'ordering': ('pk',), 'verbose_name': 'Testimonial Page Settings', 'verbose_name_plural': 'Testimonial Page Settings'},
        ),
    ]
