# Generated by Django 5.2.9 on 2025-12-31 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0005_alter_testimonialpagesettings_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonialpagesettings',
            options={'verbose_name': 'Testimonial Page Settings', 'verbose_name_plural': 'Testimonial Page Settings'},
        ),
    ]
