# Generated by Django 5.2.9 on 2026-01-03 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('testimonials', '0006_alter_testimonialpagesettings_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='client.client'),
        ),
    ]
