# Generated by Django 5.1.4 on 2026-07-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0007_alter_testimonial_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonialpagesettings',
            name='submit_heading',
            field=models.CharField(default='Partagez votre expérience', max_length=200),
        ),
        migrations.AlterField(
            model_name='testimonialpagesettings',
            name='submit_subheading',
            field=models.TextField(default="Votre avis compte énormément. Merci d'avoir fait confiance à Abasse NIANG pour votre projet !"),
        ),
        migrations.AlterField(
            model_name='testimonialpagesettings',
            name='thanks_message',
            field=models.TextField(default='Votre témoignage a bien été reçu et sera publié sur le site après validation.'),
        ),
        migrations.AlterField(
            model_name='testimonialpagesettings',
            name='thanks_subheading',
            field=models.CharField(default='Témoignage reçu', max_length=200),
        ),
        migrations.AlterField(
            model_name='testimonialpagesettings',
            name='thanks_title',
            field=models.CharField(default='Merci pour votre témoignage', max_length=200),
        ),
    ]
