# Generated by Django 6.0 on 2025-12-29 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('services', '0002_deliverable_processstep'),
        ('testimonials', '0002_testimonialpagesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BNAboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=255)),
                ('hero_subtitle', models.TextField(blank=True, null=True)),
                ('hero_badge_text', models.CharField(blank=True, max_length=100)),
                ('hero_video_url', models.URLField(blank=True, null=True)),
                ('hero_cta_text', models.CharField(blank=True, max_length=50)),
                ('hero_cta_link', models.URLField(blank=True, null=True)),
                ('service_title', models.CharField(max_length=255)),
                ('service_subtitle', models.TextField(blank=True, null=True)),
                ('project_title', models.CharField(max_length=255)),
                ('project_subtitle', models.TextField(blank=True, null=True)),
                ('pricing_title', models.CharField(max_length=255)),
                ('pricing_subtitle', models.TextField(blank=True, null=True)),
                ('experience_title', models.CharField(max_length=255)),
                ('experience_subtitle', models.TextField(blank=True, null=True)),
                ('process_title', models.CharField(max_length=255)),
                ('process_subtitle', models.TextField(blank=True, null=True)),
                ('testimonial_title', models.CharField(max_length=255)),
                ('testimonial_subtitle', models.TextField(blank=True, null=True)),
                ('faq_title', models.CharField(max_length=255)),
                ('faq_subtitle', models.TextField(blank=True, null=True)),
                ('meeting_title', models.CharField(max_length=255)),
                ('meeting_subtitle', models.TextField(blank=True, null=True)),
                ('calendly_url', models.URLField(blank=True, null=True)),
                ('contact_title', models.CharField(max_length=255)),
                ('contact_subtitle', models.TextField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('projects', models.ManyToManyField(blank=True, to='projects.project')),
                ('services', models.ManyToManyField(blank=True, to='services.service')),
                ('testimonials', models.ManyToManyField(blank=True, to='testimonials.testimonial')),
            ],
        ),
        migrations.CreateModel(
            name='BNFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='bn.bnaboutpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BNPricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('features', models.TextField(help_text='One feature per line')),
                ('featured', models.BooleanField(default=False)),
                ('cta_text', models.CharField(blank=True, max_length=50)),
                ('cta_link', models.URLField(blank=True, null=True)),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_plans', to='bn.bnaboutpage')),
            ],
        ),
        migrations.CreateModel(
            name='BNProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='bn.bnaboutpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
